**Asignatura**: SNS  
**Número de actividad**: Actividad 3_1  
**Fecha**: 20/12/2024  
**Alumno**: Pedro García Ramírez   

24_25

Actividad 3.1 - Métricas de error **para** los **problemas de regresión**

A partir de los ejemplos indicados realizar los ejercicios propuestos

# MAE: Mean Absolute Error (Error Absoluto Medio)

La métrica **MAE** evalúa el promedio de las diferencias absolutas entre los valores reales y predichos, indicando qué tan cerca están las predicciones de los valores reales en promedio.
## Fórmula:
$$
\text{MAE} = \frac{1}{n} \sum_{i=1}^{n} \left| y_{\text{true}, i} - y_{\text{pred}, i} \right|
$$
### Términos:
- **$ n $**: Número total de observaciones.
- **$y_{\text{true},i}$**: Valor verdadero del \(i\)-ésimo dato.
- **$y_{\text{pred},i}$**: Valor predicho del \(i\)-ésimo dato.
- **$\vert \cdot \vert$**: Valor absoluto de la diferencia entre los valores verdaderos y predichos.

## Interpretación:
Un valor de **MAE** más bajo indica un mejor ajuste del modelo a los datos, ya que los errores absolutos promedio son menores.

In [1]:
#Error absoluto medio - mae
from sklearn.metrics import mean_absolute_error
# Ejemplo 1
y_true = [2.5, 0, 2, 8]
y_pred = [2.5, 0, 2, 8]
mean_absolute_error(y_true, y_pred)


0.0

## MAE 2 VECTORES

In [2]:
# Ejer 1: Crear dos vectores/arrays de valores ciertos y valores previstos, y calcular el mae.
# ¿Qué valores deberían de tener el array pred para que el error fuese 0? ¿y para que error fuese de 0.25?
from sklearn.metrics import mean_absolute_error

# Valores ciertos (reales)
y_true = [1, 2, 3, 4, 5]

# Valores previstos (predicciones)
y_pred = [0.1, 0.2, 0.3, 0.4, 0.5]

# Valores previstos (predicciones) para mae 0%, mismos valores que y_true
y_pred_0 = [1, 2, 3, 4, 5]

# Valores previstos (predicciones) para mae 0.25%, añadir 0.25 a cada valor de y_true
error_mae = 0.25 # Porcentaje de error que queremos obtener
c = error_mae  # Error uniforme basado en el MAE deseado
y_pred_025 = [val + c for val in y_true]

#Calculos utilizando mean_absolute_error de sklearn.metrics
mae = mean_absolute_error(y_true, y_pred) #Calculo de mae
mae_0 = mean_absolute_error(y_true, y_pred_0) #Calculo de mae 0%
mae_025 = mean_absolute_error(y_true, y_pred_025) #Calculo de mae 0.25%

#Mostramos valores en pantalla
print(f"""Tenemos un vector de valores verdaderos: \033[1m{y_true}\033[0m
y otro de valores previstos: \033[1m{y_pred}\033[0m.
El Error Absoluto Medio (\033[1mMAE\033[0m) es de: \033[1m{mae:.3}%\033[0m.

Tenemos un vector de valores verdaderos: \033[1m{y_true}\033[0m.
Para que el Error Aboludo Medio (\033[1mMAE\033[0m) sea \033[1m{mae_0:.3}%\033[0m,
el vector de valores previstos debe coincidir
exactamente con los valores verdaderos: \033[1m{y_pred_0}\033[0m.

Por otro lado, si deseamos que el \033[1mMAE\033[0m sea de \033[1m{mae_025}%\033[0m,
basta con introducir un error uniforme al vector de valores verdaderos.
El nuevo vector de valores previstos sería: \033[1m{y_pred_025}\033[0m.

\033[1mNota\033[0m: Los valores de las métricas de error,
como MAE y MSE, están representados en \033[1mtantos por 1\033[0m. Por ejemplo:
- Un valor de ( 0.25 ) equivale al ( 25% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.
""")


Tenemos un vector de valores verdaderos: [1, 2, 3, 4, 5]
y otro de valores previstos: [0.1, 0.2, 0.3, 0.4, 0.5].
El Error Absoluto Medio (MAE) es de: 2.7%.

Tenemos un vector de valores verdaderos: [1, 2, 3, 4, 5].
Para que el Error Aboludo Medio (MAE) sea 0.0%,
el vector de valores previstos debe coincidir
exactamente con los valores verdaderos: [1, 2, 3, 4, 5].

Por otro lado, si deseamos que el MAE sea de 0.25%,
basta con introducir un error uniforme al vector de valores verdaderos.
El nuevo vector de valores previstos sería: [1.25, 2.25, 3.25, 4.25, 5.25].

Nota: Los valores de las métricas de error,
como MAE y MSE, están representados en tantos por 1. Por ejemplo:
- Un valor de ( 0.25 ) equivale al ( 25% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.



## MAE MATRIZ

In [3]:
# Ejemplo 2
y_true = [[0.5, 1], [-1, 1], [7, -6]]
y_pred = [[0, 2], [-1, 2], [8, -5]]
mean_absolute_error(y_true, y_pred)

0.75

In [5]:
# Ejer 2: Crear dos matrices/arrays de valores ciertos y valores previstos, y calcular el mae.
# ¿Qué valores deberían de tener el array pred para que el error fuese 0? ¿y para que error fuese de 0.33?
from sklearn.metrics import mean_absolute_error
import numpy as np

# Valores ciertos (reales): matriz de 2x3
y_true = np.array([[1, 2, 3], [4, 5, 6]])

# Valores previstos (predicciones)
y_pred = np.array([[1.2, 2.2, 3.2], [4.2, 5.2, 6.2]])

# Valores previstos (predicciones) para mae 0%: mismos valores que y_true
y_pred_0 = np.array([[1, 2, 3], [4, 5, 6]])

# Valores previstos (predicciones) para mae 0.33%: añadir 0.33 a cada valor de y_true
error_mae = 0.33  # Porcentaje de error deseado
c = error_mae  # Error uniforme basado en el MAE deseado
y_pred_033 = y_true + c  # Añadir el mismo error a cada elemento

# Cálculos utilizando mean_absolute_error de sklearn.metrics
# Se aplanan las matrices para calcular el MAE porque la función trabaja con vectores
mae = mean_absolute_error(y_true.flatten(), y_pred.flatten()) # Cálculo de mae
mae_0 = mean_absolute_error(y_true.flatten(), y_pred_0.flatten()) # Cálculo de mae 0%
mae_033 = round(mean_absolute_error(y_true.flatten(), y_pred_033.flatten()), 2) # Cálculo de mae 0.33% con dos decimales

# Mostramos valores en pantalla
print(f"""Tenemos una matriz de valores verdaderos:
\033[1m{y_true}\033[0m
y otra matriz de valores previstos:
\033[1m{y_pred}\033[0m
El Error Absoluto Medio (\033[1mMAE\033[0m) es de: \033[1m{mae:.3}%\033[0m.

Tenemos una matriz de valores verdaderos:
\033[1m{y_true}\033[0m
Para que el Error Absoluto Medio (\033[1mMAE\033[0m) sea \033[1m{mae_0:.3}%\033[0m,
la matriz de valores previstos debe coincidir exactamente con
la matriz de valores verdaderos:
\033[1m{y_pred_0}\033[0m.

Por otro lado, si deseamos que el \033[1mMAE\033[0m sea de \033[1m{mae_033}%\033[0m,
basta con introducir un error uniforme a la matriz de valores verdaderos.
La nueva matriz de valores previstos sería:
\033[1m{y_pred_033}\033[0m.

\033[1mNota\033[0m: Los valores de las métricas de error,
como MAE y MSE, están representados en \033[1mtantos por 1\033[0m. Por ejemplo:
- Un valor de ( 0.33 ) equivale al ( 33% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.
""")


Tenemos una matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]]
y otra matriz de valores previstos:
[[1.2 2.2 3.2]
 [4.2 5.2 6.2]]
El Error Absoluto Medio (MAE) es de: 0.2%.

Tenemos una matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]]
Para que el Error Absoluto Medio (MAE) sea 0.0%,
la matriz de valores previstos debe coincidir exactamente con
la matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]].

Por otro lado, si deseamos que el MAE sea de 0.33%,
basta con introducir un error uniforme a la matriz de valores verdaderos.
La nueva matriz de valores previstos sería:
[[1.33 2.33 3.33]
 [4.33 5.33 6.33]].

Nota: Los valores de las métricas de error,
como MAE y MSE, están representados en tantos por 1. Por ejemplo:
- Un valor de ( 0.33 ) equivale al ( 33% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.



# MSE: Mean Squared Error (Error Cuadrático Medio)
El **MSE** es una métrica utilizada para medir el promedio de los errores al cuadrado entre los valores reales $( y_{\text{true}} $) y los valores predichos $( y_{\text{pred}} $).
## Fórmula:
$$
\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} \left( y_{\text{true}, i} - y_{\text{pred}, i} \right)^2
$$
#### Términos:
- **$ n $**: Número total de observaciones.
- **$ y_{\text{true}, i} $**: Valor verdadero del \(i\)-ésimo dato.
- **$y_{\text{pred}, i} $**: Valor predicho del \(i\)-ésimo dato.
- **$ \left( y_{\text{true}, i} - y_{\text{pred}, i} \right)^2 $**: Cuadrado de la diferencia entre los valores reales y predichos.

## Interpretación:
El **MSE** mide el promedio de los errores al cuadrado, penalizando errores grandes más severamente que los pequeños.  
- **Un valor de MSE más bajo indica un mejor ajuste del modelo a los datos.**
- Es especialmente útil para detectar valores atípicos, ya que los errores grandes tienen un impacto mayor debido a la operación de elevar al cuadrado.

In [ ]:
# Error cuadrático medio - mse
from sklearn.metrics import mean_squared_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_squared_error(y_true, y_pred)


0.375

## MSE 2 VECTORES

In [6]:
# Ejer 3: Crear dos vectores/arrays de valores ciertos y valores previstos, y calcular el mse.
# ¿Qué valores deberían de tener el array pred para que el error fuese 0? ¿y para que error fuese de 0.25?
# Nota: Es muy interesante comparar los resultados al aplicaer mae y mse sobre el mismo conjunto de datos. Podrás obervar
# que mse "penaliza más" (es decir, el número que se obtiene es mayor) con las diferencias entre los valores originales y los predichos que mae
from sklearn.metrics import mean_squared_error

# Valores ciertos (reales): vector
y_true = [1, 2, 3, 4, 5]

# Valores previstos (predicciones)
y_pred= [0.1, 0.2, 0.3, 0.4, 0.5]

# Valores previstos (predicciones) para mse 0%: mismos valores que y_true
y_pred_0 = [1, 2, 3, 4, 5]

# Valores previstos (predicciones) para mse 25%: calcular un desplazamiento uniforme
error_mse = 0.25 # Porcentaje de error que queremos obtener
c = error_mse**0.5  # Error uniforme basado en el MSE deseado
y_pred_025 = [val + c for val in y_true]

# Cálculos utilizando mean_squared_error de sklearn.metrics
mse = mean_squared_error(y_true, y_pred) # Cálculo de mse
mse_0 = mean_squared_error(y_true, y_pred_0) # Cálculo de mse 0%
mse_025 = mean_squared_error(y_true, y_pred_025) #Cálculo de mse 25%

# Mostramos valores en pantalla
print(f"""Tenemos un vector de valores verdaderos:\n\033[1m{y_true}\033[0m
y otro de valores previstos \n\033[1m{y_pred}\033[0m.
El Error Cuadrático Medio (\033[1mMSE\033[0m) es de: \033[1m{mse:.3}%\033[0m.

Tenemos un vector de valores verdaderos:\n\033[1m{y_true}\033[0m.
Para que el Error Cuadrático Medio (\033[1mMSE\033[0m) sea \033[1m{mse_0:.3}%\033[0m,
el vector de valores previstos debe coincidir exactamente con los valores verdaderos:\n\033[1m{y_pred_0}\033[0m.

Por otro lado, si deseamos que el \033[1mMSE\033[0m sea de \033[1m{mse_025}%\033[0m,
sabemos que el MSE es el promedio de los \033[1merrores cuadrados\033[0m.
Si introducimos un error uniforme \033[1m{c}\033[0m a cada elemento del vector,
este \033[1m{c}\033[0m será igual a la \033[1mraíz cuadrada\033[0m del MSE propuesto.
Al sumar este error uniforme al vector de valores verdaderos,
obtenemos el nuevo vector de valores previstos:
\033[1m{y_pred_025}\033[0m.

\033[1mNota\033[0m: Los valores de las métricas de error,
como MAE y MSE, están representados en \033[1mtantos por 1\033[0m. Por ejemplo:
- Un valor de ( 0.25 ) equivale al ( 25% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.
""")

Tenemos un vector de valores verdaderos:
[1, 2, 3, 4, 5]
y otro de valores previstos 
[0.1, 0.2, 0.3, 0.4, 0.5].
El Error Cuadrático Medio (MSE) es de: 8.91%.

Tenemos un vector de valores verdaderos:
[1, 2, 3, 4, 5].
Para que el Error Cuadrático Medio (MSE) sea 0.0%,
el vector de valores previstos debe coincidir exactamente con los valores verdaderos:
[1, 2, 3, 4, 5].

Por otro lado, si deseamos que el MSE sea de 0.25%,
sabemos que el MSE es el promedio de los errores cuadrados.
Si introducimos un error uniforme 0.5 a cada elemento del vector,
este 0.5 será igual a la raíz cuadrada del MSE propuesto.
Al sumar este error uniforme al vector de valores verdaderos,
obtenemos el nuevo vector de valores previstos:
[1.5, 2.5, 3.5, 4.5, 5.5].

Nota: Los valores de las métricas de error,
como MAE y MSE, están representados en tantos por 1. Por ejemplo:
- Un valor de ( 0.25 ) equivale al ( 25% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.



## MSE MATRIZ

In [7]:
# Ejer 4: Crear dos matrices/arrays de valores ciertos y valores previstos, y calcular el mse.
# ¿Qué valores deberían de tener el array pred para que el error fuese 0? ¿y para que error fuese de 0.33?
from sklearn.metrics import mean_squared_error
import numpy as np

# Valores ciertos (reales): matriz
y_true = np.array([[1, 2, 3], [4, 5, 6]])

# Valores previstos (predicciones)
y_pred = np.array([[1.2, 2.2, 3.2], [4.2, 5.2, 6.2]])

# Valores previstos (predicciones) para mse 0%: mismos valores que y_true
y_pred_0 = np.array([[1, 2, 3], [4, 5, 6]])

# Valores previstos (predicciones) para mse 33%: calcular un desplazamiento uniforme
error_mse = 0.33  # Porcentaje de error que queremos obtener
c = error_mse**0.5  # Error uniforme basado en el MSE deseado
y_pred_033 = y_true + c  # Sumamos el desplazamiento uniforme a cada elemento

# Cálculos utilizando mean_squared_error de sklearn.metrics
mse = mean_squared_error(y_true.flatten(), y_pred.flatten())  # Cálculo de mse
mse_0 = mean_squared_error(y_true.flatten(), y_pred_0.flatten())  # Cálculo de mse 0%
mse_033 = mean_squared_error(y_true.flatten(), y_pred_033.flatten())  # Cálculo de mse 33%

# Mostramos valores en pantalla
print(f"""Tenemos una matriz de valores verdaderos:
\033[1m{y_true}\033[0m
y otra matriz de valores previstos:
\033[1m{y_pred}\033[0m
El Error Cuadrático Medio (\033[1mMSE\033[0m) es de: \033[1m{mse:.3}%\033[0m

Tenemos una matriz de valores verdaderos:\n\033[1m{y_true}\033[0m.
Para que el Error Cuadrático Medio (\033[1mMSE\033[0m) sea \033[1m{mse_0:.3}%\033[0m,
la matriz de valores previstos debe coincidir exactamente con los valores verdaderos:\n\033[1m{y_pred_0}\033[0m.

Por otro lado, si deseamos que el \033[1mMSE\033[0m sea de \033[1m{mse_033:.3}%\033[0m,
sabemos que el \033[1mMSE\033[0m es el promedio de los \033[1merrores cuadrados\033[0m.
Si introducimos un error uniforme \033[1m{c:.4}\033[0m a cada elemento de la matriz,
este \033[1m{c:.4}\033[0m será igual a la \033[1mraíz cuadrada\033[0m del \033[1mMSE\033[0m propuesto.
Al sumar este error uniforme a la matriz de valores verdaderos,
obtenemos la nueva matriz de valores previstos:\n\033[1m{y_pred_033}\033[0m.

\033[1mNota\033[0m: Los valores de las métricas de error,
como MAE y MSE, están representados en \033[1mtantos por 1\033[0m. Por ejemplo:
- Un valor de ( 0.33 ) equivale al ( 33% ).
- Si deseas expresar el error como porcentaje, simplemente multiplica el resultado por 100.
""")

Tenemos una matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]]
y otra matriz de valores previstos:
[[1.2 2.2 3.2]
 [4.2 5.2 6.2]]
El Error Cuadrático Medio (MSE) es de: 0.04%

Tenemos una matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]].
Para que el Error Cuadrático Medio (MSE) sea 0.0%,
la matriz de valores previstos debe coincidir exactamente con los valores verdaderos:
[[1 2 3]
 [4 5 6]].

Por otro lado, si deseamos que el MSE sea de 0.33%,
sabemos que el MSE es el promedio de los errores cuadrados.
Si introducimos un error uniforme 0.5745 a cada elemento de la matriz,
este 0.5745 será igual a la raíz cuadrada del MSE propuesto.
Al sumar este error uniforme a la matriz de valores verdaderos,
obtenemos la nueva matriz de valores previstos:
[[1.57445626 2.57445626 3.57445626]
 [4.57445626 5.57445626 6.57445626]].

Nota: Los valores de las métricas de error,
como MAE y MSE, están representados en tantos por 1. Por ejemplo:
- Un valor de ( 0.33 ) equivale al ( 33% ).
- Si deseas expresar 

# MAPE: Mean Absolute Percentage Error (Error Porcentual Absoluto Medio)

El **MAPE** es una métrica utilizada para medir la magnitud promedio del error relativo absoluto, expresado como porcentaje, entre los valores reales $( y_{\text{true}} $) y los valores predichos $( y_{\text{pred}} $).

## Fórmula:
$$
\text{MAPE} = \frac{1}{n} \sum_{i=1}^{n} \left| \frac{y_{\text{true}, i} - y_{\text{pred}, i}}{y_{\text{true}, i}} \right| \times 100
$$

### Términos:
- **$ n $**: Número total de observaciones.
- **$ y_{\text{true}, i} $**: Valor verdadero del \(i\)-ésimo dato.
- **$ y_{\text{pred}, i} $**: Valor predicho del \(i\)-ésimo dato.
- **$ \left| \cdot \right| $**: Valor absoluto.
- **$ \frac{y_{\text{true}, i} - y_{\text{pred}, i}}{y_{\text{true}, i}} $**: Error relativo entre el valor verdadero y el predicho.

## Interpretación:
El **MAPE** evalúa el error promedio relativo en términos porcentuales.  
- **Un valor de MAPE bajo indica una alta precisión** del modelo.  
- **Un MAPE de 0%** significa que las predicciones coinciden exactamente con los valores reales.  
- Es importante tener en cuenta que el **MAPE no está definido si $ y_{\text{true}, i} = 0 $**, ya que implica una división por cero.


In [ ]:
# Error de porcentaje absoluto medio - mape
from sklearn.metrics import mean_absolute_percentage_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
mean_absolute_percentage_error(y_true, y_pred)

0.3273809523809524

## MAPE 2 VECTORES

In [8]:
# Ejer 5: Crear dos vectores/arrays de valores ciertos y valores previstos, y calcular el mape.
# ¿Qué valores deberían de tener el array pred para que el error fuese 0?
from sklearn.metrics import mean_absolute_percentage_error

# Valores ciertos (reales)
y_true = [1, 2, 3, 4, 5]

# Valores previstos (predicciones)
y_pred = [2, 4, 6, 8, 10]

# Valores previstos (predicciones) para mape 0%: mismos valores que y_true
y_pred_0 = [1, 2, 3, 4, 5]

# Cálculo del MAPE utilizando mean_absolute_percentage_error de sklearn.metrics
mape = mean_absolute_percentage_error(y_true, y_pred)  # Cálculo de mape
mape_0 = mean_absolute_percentage_error(y_true, y_pred_0)  # Cálculo de mape 0%


# Mostramos valores en pantalla
print(f"""Tenemos un vector de valores verdaderos:
\033[1m{y_true}\033[0m
y otro vector de valores previstos:
\033[1m{y_pred}\033[0m
El Error Porcentual Absoluto Medio (\033[1mMAPE\033[0m) es de: \033[1m{mape:.2}%\033[0m

Tenemos un vector de valores verdaderos:\n\033[1m{y_true}\033[0m
Para que el Error Porcentual Absoluto Medio (\033[1mMAPE\033[0m) sea \033[1m{mape_0:.3}%\033[0m,
el vector de valores previstos debe coincidir
con el vector de valores verdaderos:
\033[1m{y_pred_0}\033[0m
""")

Tenemos un vector de valores verdaderos:
[1, 2, 3, 4, 5]
y otro vector de valores previstos:
[2, 4, 6, 8, 10]
El Error Porcentual Absoluto Medio (MAPE) es de: 1.0%

Tenemos un vector de valores verdaderos:
[1, 2, 3, 4, 5]
Para que el Error Porcentual Absoluto Medio (MAPE) sea 0.0%,
el vector de valores previstos debe coincidir
con el vector de valores verdaderos:
[1, 2, 3, 4, 5]



## MAPE MATRIZ

In [9]:
# Ejer 6: Crear dos matrices/arrays de valores ciertos y valores previstos, y calcular el MAPE.
# ¿Qué valores deberían de tener el array pred para que el error fuese 0?
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

# Valores ciertos (reales): matriz
y_true = np.array([[1, 2, 3], [4, 5, 6]])

# Valores previstos (predicciones)
y_pred = np.array([[1.2, 2.2, 3.2], [4.2, 5.2, 6.2]])

# Valores previstos (predicciones) para mape 0%: mismos valores que y_true
y_pred_0 = np.array([[1, 2, 3], [4, 5, 6]])

# Cálculo del MAPE utilizando mean_absolute_percentage_error de sklearn.metrics
mape = mean_absolute_percentage_error(y_true.flatten(), y_pred.flatten())  # Cálculo de mape
mape_0 = mean_absolute_percentage_error(y_true.flatten(), y_pred_0.flatten())  # Cálculo de mape 0%

# Mostramos valores en pantalla
print(f"""Tenemos una matriz de valores verdaderos:
\033[1m{y_true}\033[0m
y otra matirz de valores previstos:
\033[1m{y_pred}\033[0m
El Error Porcentual Absoluto Medio (\033[1mMAPE\033[0m) es de: \033[1m{mape:.2}%\033[0m

Tenemos una matriz de valores verdaderos:\n\033[1m{y_true}\033[0m
Para que el Error Porcentual Absoluto Medio (\033[1mMAPE\033[0m) sea \033[1m{mape_0:.2}%\033[0m,
la matriz de valores previstos debe coincidir exactamente con los valores verdaderos:\n\033[1m{y_pred_0}\033[0m
""")

Tenemos una matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]]
y otra matirz de valores previstos:
[[1.2 2.2 3.2]
 [4.2 5.2 6.2]]
El Error Porcentual Absoluto Medio (MAPE) es de: 0.082%

Tenemos una matriz de valores verdaderos:
[[1 2 3]
 [4 5 6]]
Para que el Error Porcentual Absoluto Medio (MAPE) sea 0.0%,
la matriz de valores previstos debe coincidir exactamente con los valores verdaderos:
[[1 2 3]
 [4 5 6]]

